// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Qzg62jvFSHiV1UCgTrtA3QMWgMSvC7M',
    appId: '1:1025226411433:web:03e6d906aeed3c8bb288b8',
    messagingSenderId: '1025226411433',
    projectId: 'booking-hotel-6a495',
    authDomain: 'booking-hotel-6a495.firebaseapp.com',
    storageBucket: 'booking-hotel-6a495.appspot.com',
    measurementId: 'G-84NB97P3XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOihfeIUdHjkDyYVWSHouQcnZYbkqGnK0',
    appId: '1:1025226411433:android:a000b2061169864cb288b8',
    messagingSenderId: '1025226411433',
    projectId: 'booking-hotel-6a495',
    storageBucket: 'booking-hotel-6a495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtFHiiILLH-rgYgakRQuxhzqiMyHlAOc4',
    appId: '1:1025226411433:ios:79acd8c232677ec6b288b8',
    messagingSenderId: '1025226411433',
    projectId: 'booking-hotel-6a495',
    storageBucket: 'booking-hotel-6a495.appspot.com',
    iosBundleId: 'com.example.bookingHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtFHiiILLH-rgYgakRQuxhzqiMyHlAOc4',
    appId: '1:1025226411433:ios:d1bd653a787ca4b7b288b8',
    messagingSenderId: '1025226411433',
    projectId: 'booking-hotel-6a495',
    storageBucket: 'booking-hotel-6a495.appspot.com',
    iosBundleId: 'com.example.bookingHotel.RunnerTests',
  );
}
